[package]
name = "indifferentiable-hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-bls12-377 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-serialize = { version = "^0.3.0", default-features = false }

sha2 = { version = "^0.10.0", default-features = false }

criterion = "0.3.4"

[dev-dependencies]
itoa = "1.0.2"
ark-ec-m2c = { package = "ark-ec", git = "https://github.com/mmagician/algebra/", branch = "map-to-curve-tests", features = [ "parallel" ] }
ark-ff-m2c = { package = "ark-ff", git = "https://github.com/mmagician/algebra/", branch = "map-to-curve-tests", features = [ "parallel" ] }
ark-test-curves = { git = "https://github.com/mmagician/algebra/", branch = "map-to-curve-tests", features = [ "parallel", "bls12_381_curve" ] }

[[bench]]
name = "bench"
harness = false

# To be removed in the new release.
[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std"}